import type { Member, EfitEvent, Project, Contest, Notice, WallItem, RecruitmentDepartment } from './types';

// ─── Members ───
// TODO: Populate from CSV file when available
export const MOCK_MEMBERS: Member[] = [];

// ─── Events ───
export const MOCK_EVENTS: EfitEvent[] = [
  {
    id: 'evt-1',
    slug: 'efit-codesprint-2026',
    title: 'EFIT CodeSprint 2026',
    description: 'A 24-hour competitive coding hackathon for all CS&IT students.',
    longDescription: 'EFIT CodeSprint is the flagship hackathon organized by the CS&IT student body. Teams of up to 4 members compete to build innovative solutions to real-world problems. This year\'s theme focuses on sustainable technology and campus innovation.',
    category: 'Hackathon',
    date: '2026-10-20',
    endDate: '2026-10-21',
    time: '10:00 AM',
    venue: 'CSE Block, Lab 301–305',
    mode: 'Offline',
    image: '',
    organizedBy: 'EFIT Technical Team',
    coordinators: [],
    rules: [
      'Teams of 2–4 members',
      'All team members must be KL University students',
      'Use of AI tools is permitted but must be disclosed',
      'Projects must be built from scratch during the event',
      'Final submission includes source code and a 5-minute demo',
    ],
    eligibility: 'All B.Tech CSE & IT students',
    timeline: [
      { time: '10:00 AM', title: 'Registration & Check-in', description: 'Collect badges and settle in' },
      { time: '11:00 AM', title: 'Opening Ceremony', description: 'Problem statements revealed' },
      { time: '12:00 PM', title: 'Hacking Begins', description: '24 hours of building' },
      { time: '12:00 PM (Next Day)', title: 'Submissions Close', description: 'Upload your projects' },
      { time: '02:00 PM', title: 'Demos & Judging', description: '5-minute presentations' },
      { time: '04:00 PM', title: 'Awards Ceremony', description: 'Winners announced' },
    ],
    registrationOpen: true,
    maxParticipants: 200,
    currentRegistrations: 87,
    tags: ['hackathon', 'coding', 'competition'],
  },
  {
    id: 'evt-2',
    slug: 'full-stack-workshop',
    title: 'Full Stack Development Workshop',
    description: 'Hands-on workshop covering React, Node.js, and MongoDB.',
    longDescription: 'Learn to build production-grade web applications from scratch. This intensive 2-day workshop covers frontend development with React 19, backend APIs with Node.js and Express, database design with MongoDB, and deployment with Docker.',
    category: 'Workshop',
    date: '2026-10-12',
    time: '09:30 AM',
    venue: 'Seminar Hall, CSE Block',
    mode: 'Offline',
    image: '',
    organizedBy: 'EFIT Technical Team',
    coordinators: [],
    rules: ['Bring your own laptop', 'Pre-install Node.js and VS Code'],
    eligibility: 'All B.Tech students',
    timeline: [
      { time: '09:30 AM', title: 'Setup & Introduction', description: 'Environment configuration' },
      { time: '10:30 AM', title: 'React Fundamentals', description: 'Components, hooks, state' },
      { time: '02:00 PM', title: 'Backend with Express', description: 'REST APIs and middleware' },
      { time: '04:00 PM', title: 'MongoDB & Integration', description: 'Database design and CRUD' },
    ],
    registrationOpen: true,
    maxParticipants: 80,
    currentRegistrations: 42,
    tags: ['workshop', 'fullstack', 'react', 'nodejs'],
  },
  {
    id: 'evt-3',
    slug: 'career-in-tech-talk',
    title: 'Career in Tech: Industry Panel',
    description: 'Alumni panel discussion on career paths in software engineering.',
    longDescription: 'Join us for an insightful panel discussion featuring KL University alumni who have built successful careers at top tech companies. Topics include interview preparation, skill development, and navigating the tech industry landscape.',
    category: 'Talk',
    date: '2026-11-02',
    time: '03:00 PM',
    venue: 'Auditorium, Main Block',
    mode: 'Hybrid',
    image: '',
    organizedBy: 'EFIT Operations',
    coordinators: [],
    rules: [],
    eligibility: 'All students',
    timeline: [
      { time: '03:00 PM', title: 'Welcome', description: 'Introduction to panelists' },
      { time: '03:15 PM', title: 'Panel Discussion', description: 'Moderated Q&A' },
      { time: '04:30 PM', title: 'Networking', description: 'Connect with alumni' },
    ],
    registrationOpen: true,
    currentRegistrations: 156,
    tags: ['career', 'panel', 'alumni'],
  },
  {
    id: 'evt-4',
    slug: 'ui-design-challenge',
    title: 'UI Design Challenge',
    description: '48-hour design sprint for creative interface solutions.',
    longDescription: 'Put your design skills to the test in this 48-hour challenge. Participants will receive a design brief and must create a complete UI/UX solution using Figma or any design tool of their choice.',
    category: 'Competition',
    date: '2026-11-15',
    time: '10:00 AM',
    venue: 'Online',
    mode: 'Online',
    image: '',
    organizedBy: 'EFIT Creative Team',
    coordinators: [],
    rules: ['Individual participation only', 'Submissions in Figma or PDF format', 'Original work only'],
    eligibility: 'All B.Tech students',
    timeline: [],
    registrationOpen: false,
    maxParticipants: 100,
    currentRegistrations: 0,
    tags: ['design', 'ui', 'creative'],
  },
];

// ─── Projects ───
export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    slug: 'orbit',
    title: 'ORBIT',
    summary: 'Observability platform for monitoring distributed systems.',
    description: 'ORBIT is a comprehensive observability platform designed for monitoring distributed systems. It provides real-time metrics, distributed tracing, and log aggregation in a unified dashboard.',
    image: '',
    techStack: ['Next.js', 'Node.js', 'MongoDB', 'Docker', 'Grafana'],
    contributors: [],
    githubUrl: 'https://github.com/efit-kl/orbit',
    liveUrl: 'https://orbit.efit.dev',
    status: 'Active',
    featured: true,
  },
  {
    id: 'proj-2',
    slug: 'campus-connect',
    title: 'Campus Connect',
    summary: 'Real-time campus event discovery and networking platform.',
    description: 'Campus Connect helps students discover events, connect with clubs, and build their campus network. Features include event recommendations, real-time notifications, and social profiles.',
    image: '',
    techStack: ['React Native', 'Express.js', 'PostgreSQL', 'Redis'],
    contributors: [],
    githubUrl: 'https://github.com/efit-kl/campus-connect',
    status: 'Active',
    featured: true,
  },
  {
    id: 'proj-3',
    slug: 'codebase',
    title: 'CodeBase',
    summary: 'Collaborative code review and learning platform for students.',
    description: 'CodeBase is a platform where students can share code snippets, get peer reviews, and learn from each other\'s solutions to common programming challenges.',
    image: '',
    techStack: ['Next.js', 'TypeScript', 'Prisma', 'PostgreSQL'],
    contributors: [],
    githubUrl: 'https://github.com/efit-kl/codebase',
    status: 'Completed',
    featured: false,
  },
];

// ─── Contests ───
export const MOCK_CONTESTS: Contest[] = [
  {
    id: 'con-1',
    slug: 'algo-arena-2026',
    title: 'Algo Arena 2026',
    description: 'Competitive programming contest with algorithmic challenges across 3 difficulty tiers.',
    rules: ['Individual participation', 'No external help or AI tools', '3 hours duration', 'Standard I/O format'],
    deadline: '2026-10-25',
    status: 'Upcoming',
    image: '',
    problemStatement: '10 problems ranging from easy to expert level',
    maxTeamSize: 1,
    prizes: ['₹10,000 First Prize', '₹5,000 Second Prize', '₹3,000 Third Prize'],
    registrationOpen: true,
  },
  {
    id: 'con-2',
    slug: 'bug-bounty-hunt',
    title: 'Bug Bounty Hunt',
    description: 'Find and report vulnerabilities in our sandboxed web applications.',
    rules: ['Teams of 1–3', 'Only test authorized targets', 'Report format provided', 'Responsible disclosure'],
    deadline: '2026-11-10',
    status: 'Upcoming',
    image: '',
    maxTeamSize: 3,
    prizes: ['₹15,000 Most Critical', '₹8,000 Most Creative', '₹5,000 Best Report'],
    registrationOpen: true,
  },
];

// ─── Notices ───
export const MOCK_NOTICES: Notice[] = [
  {
    id: 'not-1',
    title: 'EFIT 2026–27 Recruitment Open',
    content: 'Applications are now open for all departments. Apply before October 30th to join the EFIT team for the upcoming academic year.',
    category: 'IMPORTANT',
    date: '2026-09-20',
    important: true,
    author: 'EFIT Administration',
  },
  {
    id: 'not-2',
    title: 'Smart India Hackathon 2026',
    content: 'Registration for SIH 2026 is now open. Form teams of 6 and register through the official portal. EFIT will provide mentorship for selected teams.',
    category: 'EVENT',
    date: '2026-09-18',
    important: false,
    author: 'Technical Director',
  },
  {
    id: 'not-3',
    title: 'New Projects Added',
    content: 'Three new community projects have been added to the EFIT Projects showcase. Check them out and consider contributing.',
    category: 'UPDATE',
    date: '2026-09-15',
    important: false,
    author: 'Project Lead',
  },
  {
    id: 'not-4',
    title: 'Guest Lecture: Cloud Architecture',
    content: 'AWS Solutions Architect will be conducting a guest lecture on cloud-native application design. Register through the events page.',
    category: 'GENERAL',
    date: '2026-09-12',
    important: false,
    author: 'EFIT Operations',
  },
];

// ─── Wall of KL ───
export const MOCK_WALL_ITEMS: WallItem[] = [
  {
    id: 'wall-1',
    title: 'CodeSprint 2025 Winners',
    description: 'Team Alpha wins the flagship hackathon with an AI-powered campus navigation system.',
    image: '',
    category: 'achievement',
    date: '2025-10-21',
  },
  {
    id: 'wall-2',
    title: 'SIH 2025 National Finals',
    description: 'EFIT team reaches Smart India Hackathon national finals.',
    image: '',
    category: 'hackathon',
    date: '2025-08-15',
  },
  {
    id: 'wall-3',
    title: 'Full Stack Workshop Series',
    description: '200+ students trained across 4 intensive workshops.',
    image: '',
    category: 'event',
    date: '2025-09-10',
  },
  {
    id: 'wall-4',
    title: 'ORBIT Launch',
    description: 'First community-built observability platform goes live.',
    image: '',
    category: 'project',
    date: '2025-07-01',
  },
  {
    id: 'wall-5',
    title: 'EFIT Annual Day',
    description: 'Celebrating a year of building, competing, and leading.',
    image: '',
    category: 'moment',
    date: '2026-03-15',
  },
];

// ─── Recruitment Departments ───
export const MOCK_RECRUITMENT_DEPARTMENTS: RecruitmentDepartment[] = [
  { id: 'dept-1', name: 'Technical', description: 'Build products, tools, and systems.', positions: 8, open: true },
  { id: 'dept-2', name: 'Creative', description: 'Design visual identity and experiences.', positions: 4, open: true },
  { id: 'dept-3', name: 'Events', description: 'Plan and execute workshops, hackathons.', positions: 6, open: true },
  { id: 'dept-4', name: 'Broadcasting', description: 'Manage media production and streaming.', positions: 3, open: true },
  { id: 'dept-5', name: 'Content', description: 'Write, edit, and curate content.', positions: 4, open: true },
  { id: 'dept-6', name: 'Design', description: 'UI/UX, graphics, and brand design.', positions: 3, open: true },
  { id: 'dept-7', name: 'Operations', description: 'Logistics, coordination, and management.', positions: 5, open: true },
  { id: 'dept-8', name: 'Social Media', description: 'Grow and engage the community.', positions: 3, open: true },
];
